; =========================
; SHADOW SCALABILITY SETUP
; Semi Open World (CSM)
; =========================

; ---------- MEDIUM ----------
[ShadowQuality@1]
r.Shadow.MaxResolution=2048
r.Shadow.CSM.MaxCascades=3
r.Shadow.RadiusThreshold=0.03
r.Shadow.FilterMethod=1
r.Shadow.Virtual.ResolutionLodBiasDirectional=1
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=1
r.Shadow.Virtual.ResolutionLodBiasLocal=1
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=2
r.Shadow.Virtual.MaxPhysicalPages=512
r.Shadow.DistanceScale=0.7
r.ShadowQuality=3

; ---------- HIGH ----------
[ShadowQuality@2]
r.Shadow.Virtual.ResolutionLodBiasDirectional=1
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=1
r.Shadow.Virtual.ResolutionLodBiasLocal=1
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=1.5
r.Shadow.Virtual.MaxPhysicalPages=1024
r.Shadow.DistanceScale=0.8
r.ShadowQuality=4

; ---------- EPIC ----------
[ShadowQuality@3]
r.Shadow.Virtual.ResolutionLodBiasDirectional=0
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=0
r.Shadow.Virtual.ResolutionLodBiasLocal=0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=1
r.Shadow.Virtual.MaxPhysicalPages=2048
r.Shadow.DistanceScale=0.85
r.ShadowQuality=5

[GlobalIlluminationQuality@0]
r.AOQuality=1
r.DistanceFieldAO=1
r.SSGI.Quality=1
r.AmbientOcclusionLevels=1

[ScalabilitySettings]

PerfIndexValues_ResolutionQuality="50 65 75 85 100"
